### ISSUE TITLE
simpleJSON error

### ISSUE THREAD

**Issue by abrenoch** [abrenoch/piwigo-kodi#14]
11:59:47 T:9168   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 502: Bad Gateway
                                            Traceback (most recent call last):
                                              File "C:\Users\Dave7\AppData\Roaming\Kodi\addons\piwigo-kodi-development\addon.py", line 336, in <module>
                                                populateImages(serverRequest('pwg.categories.getImages', {'order':'random', 'per_page':plugin.getSetting('limit')}))
                                              File "C:\Users\Dave7\AppData\Roaming\Kodi\addons\piwigo-kodi-development\addon.py", line 123, in serverRequest
                                                conn = opener.open(req)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 410, in open
                                                response = meth(req, response)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 523, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 448, in error
                                                return self._call_chain(*args)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 382, in _call_chain
                                                result = func(*args)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 531, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 502: Bad Gateway
                                            -->End of Python script error report<--

**Comment by abrenoch** [comment]
Seems to be happening when trying to view random photos

**Comment by abrenoch** [comment]
This was a server issue - some randoms would work other not.. turned out to be a permission error in one of the pwg_representative folders.. Correcting those permissions seems to have corrected the issue!
